Goal1 - season per game avgs

In [4]:
import pandas as pd
from nba_api.stats.endpoints import playerprofilev2

In [5]:
player_id = 1628983

In [43]:
player_profile = (playerprofilev2.PlayerProfileV2(player_id=player_id).get_data_frames())

In [44]:
player_profile

[   PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION  PLAYER_AGE  \
 0    1628983   2018-19        00  1610612746               LAC        20.0
 1    1628983   2019-20        00  1610612760               OKC        21.0
 2    1628983   2020-21        00  1610612760               OKC        22.0
 3    1628983   2021-22        00  1610612760               OKC        23.0
 4    1628983   2022-23        00  1610612760               OKC        24.0
 5    1628983   2023-24        00  1610612760               OKC        25.0
 6    1628983   2024-25        00  1610612760               OKC        26.0

    GP  GS   MIN  FGM  ...  FT_PCT  OREB  DREB  REB  AST  STL  BLK  TOV   PF  \
 0  82  73  2174  341  ...   0.800    57   175  232  270   96   45  141  175
 1  70  70  2428  478  ...   0.807    47   365  412  232   79   47  134  117
 2  35  35  1180  287  ...   0.808    19   147  166  207   27   23  106   70
 3  56  56  1942  477  ...   0.810    37   241  278  331   71   46  154  142
 4  68  68  2416  704  ...   0.905    59   270  329  371  112   65  192  192
 5  75  75  2553  796  ...   0.874    65   350  415  465  150   67  162  184
 6   6   6   189   57  ...   0.917     7    33   40   39   11    7   11   10

     PTS
 0   889
 1  1331
 2   830
 3  1371
 4  2135
 5  2254
 6   159

 [7 rows x 27 columns],
    PLAYER_ID LEAGUE_ID  TEAM_ID   GP   GS    MIN   FGM   FGA  FG_PCT  FG3M  \
 0    1628983        00        0  392  383  12881  3140  6337   0.496   463

    ...  FT_PCT  OREB  DREB   REB   AST  STL  BLK  TOV   PF   PTS
 0  ...   0.853   291  1581  1872  1915  546  300  900  890  8969

 [1 rows x 24 columns],
    PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION  PLAYER_AGE  \
 0    1628983   2018-19        00  1610612746               LAC        20.0
 1    1628983   2019-20        00  1610612760               OKC        21.0
 2    1628983   2023-24        00  1610612760               OKC        25.0

    GP  GS  MIN  FGM  ...  FT_PCT  OREB  DREB  REB  AST  STL  BLK  TOV  PF  PTS
 0   6   6  173   28  ...   0.850     4    12   16   19    6    5    5  17   82
 1   7   7  279   39  ...   0.957     3    34   37   29    7    3   15  17  114
 2  10  10  399  111  ...   0.790     8    64   72   64   13   17   22  31  302

 [3 rows x 27 columns],
    PLAYER_ID LEAGUE_ID  TEAM_ID  GP  GS  MIN  FGM  FGA  FG_PCT  FG3M  ...  \
 0    1628983        00        0  23  23  850  178  374   0.476    39  ...

    FT_PCT  OREB  DREB  REB  AST  STL  BLK  TOV  PF  PTS
 0   0.831    15   110  125  112   26   25   42  65  498

 [1 rows x 24 columns],
    PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION  PLAYER_AGE  \
 0    1628983   2022-23        00  1610616833               GNS        24.0
 1    1628983   2023-24        00  1610616834               WST        25.0

    GP  GS  MIN  FGM  ...  FT_PCT  OREB  DREB  REB  AST  STL  BLK  TOV  PF  PTS
 0   1   0   10    4  ...     0.0     2     0    2    7    0    0    0   0    9
 1   1   1   28   12  ...     0.0     2     2    4    6    1    0    0   0   31

 [2 rows x 27 columns],
    PLAYER_ID LEAGUE_ID  TEAM_ID  GP  GS  MIN  FGM  FGA  FG_PCT  FG3M  ...  \
 0    1628983        00        0   2   1   38   16   21   0.762     8  ...

    FT_PCT  OREB  DREB  REB  AST  STL  BLK  TOV  PF  PTS
 0     0.0     4     2    6   13    1    0    0   0   40

 [1 rows x 24 columns],
    PLAYER_ID SEASON_ID LEAGUE_ID  ORGANIZATION_ID SCHOOL_NAME  PLAYER_AGE  GP  \
 0    1628983   2017-18        00             2852    Kentucky        19.0  37

    GS   MIN  FGM  ...  FT_PCT  OREB  DREB  REB  AST  STL  BLK  TOV  PF  PTS
 0  24  1248  183  ...   0.822    33   120  153  189   61   18   99  62  532

 [1 rows x 27 columns],
    PLAYER_ID LEAGUE_ID  ORGANIZATION_ID  GP  GS   MIN  FGM  FGA  FG_PCT  FG3M  \
 0    1628983        00                0  37  24  1248  183  377   0.485    23

    ...  FT_PCT  OREB  DREB  REB  AST  STL  BLK  TOV  PF  PTS
 0  ...   0.822    33   120  153  189   61   18   99  62  532

 [1 rows x 24 columns],
    PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION  PLAYER_AGE  \
 0    1628983   2018-19        00  1610612746               LAC        20.0
 1    1628983   2019-20        00  1610612760               OKC        21.0
 2    1628983   2020-21        00  1610612760               OKC        22.0
 3    1628983   2021-22        00  1610612760               OKC        23.0
 4    1628983   2023-24        00  1610612760               OKC        25.0
 5    1628983   2024-25        00  1610612760               OKC        26.0

    GP  GS  MIN  FGM  ...  FT_PCT  OREB  DREB  REB  AST  STL  BLK  TOV  PF  PTS
 0   5   3  107   19  ...   0.625     3     9   12   19    8    1    4  13   46
 1   7   7  170   41  ...   0.879     4    28   32   19    4    3   15   9  118
 2   3   3   63   14  ...   0.727     0     7    7   12    3    2    5   3   38
 3   3   3   63   11  ...   0.571     0     7    7   14    1    2    5   6   30
 4   2   2   47    7  ...   0.833     0     7    7    8    6    2    3   1   22
 5   3   3   58   13  ...   1.000     2     7    9   12    4    2    6   3   40

 [6 rows x 27 columns],
    PLAYER_ID LEAGUE_ID  TEAM_ID  GP  GS  MIN  FGM  FGA  FG_PCT  FG3M  ...  \
 0    1628983        00        0  23  21  507  105  217   0.484    26  ...

    FT_PCT  OREB  DREB  REB  AST  STL  BLK  TOV  PF  PTS
 0   0.806     9    65   74   84   26   12   38  35  294

 [1 rows x 24 columns],
    PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION PLAYER_AGE  GP  \
 0    1628983   2018-19        00  1610612746               LAC         NR  NR
 1    1628983   2019-20        00  1610612760               OKC         NR  NR
 2    1628983   2020-21        00  1610612760               OKC         NR  NR
 3    1628983   2021-22        00  1610612760               OKC         NR  NR
 4    1628983   2022-23        00  1610612760               OKC         NR  NR
 5    1628983   2023-24        00  1610612760               OKC         NR  NR
 6    1628983   2024-25        00  1610612760               OKC         NR  NR

    GS  RANK_MIN  RANK_FGM  ...  RANK_FT_PCT  RANK_OREB  RANK_DREB  RANK_REB  \
 0  NR        74       101  ...           64        150        205       202
 1  NR         8        25  ...           64        166         27        44
 2  NR       212       106  ...           62        317        212       234
 3  NR        99        38  ...           62        227        114       144
 4  NR        33         6  ...            5        148         90       102
 5  NR        28         4  ...           18        132         49        62
 6  NR        73        12  ...           21         99         43        56

    RANK_AST  RANK_STL  RANK_BLK  RANK_TOV  RANK_PTS  RANK_EFF
 0        60        28        74        58       106       116
 1        61        33        54        48        23        30
 2        78       264       152        77        86       121
 3        37        61        65        43        30        55
 4        33         6        32        24         4         6
 5        18         1        35        38         2         6
 6        15        12        25        78        14         7

 [7 rows x 27 columns],
    PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID TEAM_ABBREVIATION PLAYER_AGE  GP  \
 0    1628983   2018-19        00  1610612746               LAC         NR  NR
 1    1628983   2019-20        00  1610612760               OKC         NR  NR
 2    1628983   2023-24        00  1610612760               OKC         NR  NR

    GS  RANK_MIN  RANK_FGM  ...  RANK_FT_PCT  RANK_OREB  RANK_DREB  RANK_REB  \
 0  NR        80        71  ...           23         97        122       118
 1  NR        46        56  ...            4        102         60        72
 2  NR        33         9  ...           35         68         20        26

    RANK_AST  RANK_STL  RANK_BLK  RANK_TOV  RANK_PTS  RANK_EFF
 0        54        56        48       109        69        75
 1        40        52        60        44        56        54
 2        15        20         9        22        11        14

 [3 rows x 27 columns],
     PLAYER_ID     GAME_ID    GAME_DATE  VS_TEAM_ID VS_TEAM_CITY  \
 0     1628983  0022400100  OCT 27 2024  1610612737      Atlanta
 1     1628983  0022400100  OCT 27 2024  1610612737      Atlanta
 2     1628983  0022400100  OCT 27 2024  1610612737      Atlanta
 3     1628983  0022400091  OCT 26 2024  1610612741      Chicago
 4     1628983  0022400075  OCT 24 2024  1610612743       Denver
 5     1628983  0022400100  OCT 27 2024  1610612737      Atlanta
 6     1628983  0022400150  NOV 02 2024  1610612746           LA
 7     1628983  0022400100  OCT 27 2024  1610612737      Atlanta
 8     1628983  0022400091  OCT 26 2024  1610612741      Chicago
 9     1628983  0022400100  OCT 27 2024  1610612737      Atlanta
 10    1628983  0022400075  OCT 24 2024  1610612743       Denver
 11    1628983  0022400140  NOV 01 2024  1610612757     Portland
 12    1628983  0022400100  OCT 27 2024  1610612737      Atlanta
 13    1628983  0022400075  OCT 24 2024  1610612743       Denver
 14    1628983  0022400100  OCT 27 2024  1610612737      Atlanta
 15    1628983  0022400125  OCT 30 2024  1610612759  San Antonio
 16    1628983  0022400100  OCT 27 2024  1610612737      Atlanta
 17    1628983  0022400100  OCT 27 2024  1610612737      Atlanta

      VS_TEAM_NAME VS_TEAM_ABBREVIATION  STAT  STAT_VALUE  STAT_ORDER  \
 0           Hawks                  ATL   PTS          35           1
 1           Hawks                  ATL   REB          11           2
 2           Hawks                  ATL  OREB           2           3
 3           Bulls                  CHI  OREB           2           3
 4         Nuggets                  DEN  OREB           2           3
 5           Hawks                  ATL  DREB           9           4
 6        Clippers                  LAC   AST           9           5
 7           Hawks                  ATL   AST           9           5
 8           Bulls                  CHI   STL           4           6
 9           Hawks                  ATL   BLK           3           7
 10        Nuggets                  DEN   BLK           3           7
 11  Trail Blazers                  POR   FGM          12           8
 12          Hawks                  ATL   FGA          24           9
 13        Nuggets                  DEN   FGA          24           9
 14          Hawks                  ATL  FG3M           3          10
 15          Spurs                  SAS  FG3A          10          11
 16          Hawks                  ATL   FTM          10          12
 17          Hawks                  ATL   FTA          11          13

                DATE_EST
 0   2024-10-27T00:00:00
 1   2024-10-27T00:00:00
 2   2024-10-27T00:00:00
 3   2024-10-26T00:00:00
 4   2024-10-24T00:00:00
 5   2024-10-27T00:00:00
 6   2024-11-02T00:00:00
 7   2024-10-27T00:00:00
 8   2024-10-26T00:00:00
 9   2024-10-27T00:00:00
 10  2024-10-24T00:00:00
 11  2024-11-01T00:00:00
 12  2024-10-27T00:00:00
 13  2024-10-24T00:00:00
 14  2024-10-27T00:00:00
 15  2024-10-30T00:00:00
 16  2024-10-27T00:00:00
 17  2024-10-27T00:00:00  ,
     PLAYER_ID     GAME_ID    GAME_DATE  VS_TEAM_ID  VS_TEAM_CITY  \
 0     1628983  0022200843  FEB 10 2023  1610612757      Portland
 1     1628983  0022200488  DEC 23 2022  1610612740   New Orleans
 2     1628983  0021900594  JAN 13 2020  1610612750     Minnesota
 3     1628983  0022200773  FEB 01 2023  1610612745       Houston
 4     1628983  0021900594  JAN 13 2020  1610612750     Minnesota
 5     1628983  0022300710  FEB 04 2024  1610612761       Toronto
 6     1628983  0022100979  MAR 08 2022  1610612749     Milwaukee
 7     1628983  0022300021  NOV 14 2023  1610612759   San Antonio
 8     1628983  0022200511  DEC 27 2022  1610612759   San Antonio
 9     1628983  0022200146  NOV 07 2022  1610612765       Detroit
 10    1628983  0021800606  JAN 08 2019  1610612766     Charlotte
 11    1628983  0022300207  NOV 18 2023  1610612744  Golden State
 12    1628983  0022301222  DEC 08 2023  1610612744  Golden State
 13    1628983  0022000495  FEB 24 2021  1610612759   San Antonio
 14    1628983  0022100234  NOV 19 2021  1610612749     Milwaukee
 15    1628983  0022200843  FEB 10 2023  1610612757      Portland
 16    1628983  0022301153  APR 09 2024  1610612758    Sacramento

      VS_TEAM_NAME VS_TEAM_ABBREVIATION  STAT  STAT_VALUE  STAT_ORDER  \
 0   Trail Blazers                  POR   PTS          44           1
 1        Pelicans                  NOP   PTS          44           1
 2    Timberwolves                  MIN   REB          20           2
 3         Rockets                  HOU  OREB           5           3
 4    Timberwolves                  MIN  DREB          18           4
 5         Raptors                  TOR   AST          14           5
 6           Bucks                  MIL   AST          14           5
 7           Spurs                  SAS   STL           7           6
 8           Spurs                  SAS   BLK           4           7
 9         Pistons                  DET   BLK           4           7
 10        Hornets                  CHA   BLK           4           7
 11       Warriors                  GSW   FGM          18           8
 12       Warriors                  GSW   FGA          30           9
 13          Spurs                  SAS  FG3M           6          10
 14          Bucks                  MIL  FG3A          12          11
 15  Trail Blazers                  POR   FTM          18          12
 16          Kings                  SAC   FTA          20          13

                DATE_EST
 0   2023-02-10T00:00:00
 1   2022-12-23T00:00:00
 2   2020-01-13T00:00:00
 3   2023-02-01T00:00:00
 4   2020-01-13T00:00:00
 5   2024-02-04T00:00:00
 6   2022-03-08T00:00:00
 7   2023-11-14T00:00:00
 8   2022-12-27T00:00:00
 9   2022-11-07T00:00:00
 10  2019-01-08T00:00:00
 11  2023-11-18T00:00:00
 12  2023-12-08T00:00:00
 13  2021-02-24T00:00:00
 14  2021-11-19T00:00:00
 15  2023-02-10T00:00:00
 16  2024-04-09T00:00:00  ,
       GAME_ID    GAME_DATE GAME_TIME LOCATION  PLAYER_TEAM_ID  \
 0  0022400163  NOV 04 2024  09:15 PM        H      1610612760

   PLAYER_TEAM_CITY PLAYER_TEAM_NICKNAME PLAYER_TEAM_ABBREVIATION  VS_TEAM_ID  \
 0    Oklahoma City              Thunder                      OKC  1610612753

   VS_TEAM_CITY VS_TEAM_NICKNAME VS_TEAM_ABBREVIATION
 0      Orlando            Magic                  ORL  ]

In [53]:
careertotalsregularseason = player_profile[0]

In [54]:
careertotalsregularseason

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1628983,2018-19,00,1610612746,LAC,20.0,82,73,2174,341,...,0.800,57,175,232,270,96,45,141,175,889
1,1628983,2019-20,00,1610612760,OKC,21.0,70,70,2428,478,...,0.807,47,365,412,232,79,47,134,117,1331
2,1628983,2020-21,00,1610612760,OKC,22.0,35,35,1180,287,...,0.808,19,147,166,207,27,23,106,70,830
3,1628983,2021-22,00,1610612760,OKC,23.0,56,56,1942,477,...,0.810,37,241,278,331,71,46,154,142,1371
4,1628983,2022-23,00,1610612760,OKC,24.0,68,68,2416,704,...,0.905,59,270,329,371,112,65,192,192,2135
5,1628983,2023-24,00,1610612760,OKC,25.0,75,75,2553,796,...,0.874,65,350,415,465,150,67,162,184,2254
6,1628983,2024-25,00,1610612760,OKC,26.0,6,6,189,57,...,0.917,7,33,40,39,11,7,11,10,159

In [46]:
careertotalspostseason_df = player_profile[2]

In [49]:
careertotalspostseason_df

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1628983,2018-19,00,1610612746,LAC,20.0,6,6,173,28,...,0.850,4,12,16,19,6,5,5,17,82
1,1628983,2019-20,00,1610612760,OKC,21.0,7,7,279,39,...,0.957,3,34,37,29,7,3,15,17,114
2,1628983,2023-24,00,1610612760,OKC,25.0,10,10,399,111,...,0.790,8,64,72,64,13,17,22,31,302

In [51]:
careertotalsallstarseason_df = player_profile[4]

In [52]:
careertotalsallstarseason_df

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1628983,2022-23,00,1610616833,GNS,24.0,1,0,10,4,...,0.0,2,0,2,7,0,0,0,0,9
1,1628983,2023-24,00,1610616834,WST,25.0,1,1,28,12,...,0.0,2,2,4,6,1,0,0,0,31