In [ ]:
#DS Imports
import pandas as pd

#Fuzzy Finder Algorithm
from thefuzz import fuzz
from thefuzz import process

#Stats API
from nba_api.stats.library import data

In [4]:
players = pd.DataFrame(data.players)

In [7]:
players.head(35)

          0             1         2                    3      4
0     76001     Abdelnaby      Alaa       Alaa Abdelnaby  False
1     76002    Abdul-Aziz      Zaid      Zaid Abdul-Aziz  False
2     76003  Abdul-Jabbar    Kareem  Kareem Abdul-Jabbar  False
3        51    Abdul-Rauf   Mahmoud   Mahmoud Abdul-Rauf  False
4      1505   Abdul-Wahad     Tariq    Tariq Abdul-Wahad  False
5       949   Abdur-Rahim   Shareef  Shareef Abdur-Rahim  False
6     76005     Abernethy       Tom        Tom Abernethy  False
7     76006          Able    Forest          Forest Able  False
8     76007     Abramovic      John       John Abramovic  False
9    203518       Abrines      Alex         Alex Abrines  False
10  1630173       Achiuwa  Precious     Precious Achiuwa   True
11   101165         Acker      Alex           Alex Acker  False
12    76008      Ackerman    Donald      Donald Ackerman  False
13    76009         Acres      Mark           Mark Acres  False
14    76010         Acton   Charles        Charles Acton  False
15   203112           Acy    Quincy           Quincy Acy  False
16    76011         Adams     Alvan          Alvan Adams  False
17    76012         Adams       Don            Don Adams  False
18   200801         Adams    Hassan         Hassan Adams  False
19  1629121         Adams    Jaylen         Jaylen Adams  False
20   203919         Adams    Jordan         Jordan Adams  False
21      149         Adams   Michael        Michael Adams  False
22   203500         Adams    Steven         Steven Adams  False
23      912       Addison    Rafael       Rafael Addison  False
24  1628389       Adebayo       Bam          Bam Adebayo   True
25  1629061          Adel      Deng            Deng Adel  False
26    76015       Adelman      Rick         Rick Adelman  False
27   202399        Adrien      Jeff          Jeff Adrien  False
28   201167       Afflalo     Arron        Arron Afflalo  False
29  1630534        Agbaji     Ochai         Ochai Agbaji   True
30   200772          Ager   Maurice         Maurice Ager  False
31    76016       Aguirre      Mark         Mark Aguirre  False
32   201336        Ahearn     Blake         Blake Ahearn  False
33    76017         Ainge     Danny          Danny Ainge  False
34   201582        Ajinca    Alexis        Alexis Ajinca  False

In [ ]:
def name_match(search_string -> str, search_list -> list):
    for i in search_list:
        for x in range(len(i)):

In [ ]:
def player_search():